# Generated by Django 5.1.7 on 2025-06-05 18:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExerciseTip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(5)])),
                ('content', models.TextField(validators=[django.core.validators.MinLengthValidator(20)])),
                ('category', models.CharField(choices=[('STRENGTH', 'Trening siłowy'), ('CARDIO', 'Cardio'), ('FLEXIBILITY', 'Rozciąganie'), ('NUTRITION', 'Odżywianie'), ('RECOVERY', 'Regeneracja')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
