# Generated by Django 5.1.7 on 2025-06-05 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_exercisetip'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='current_weight_kg',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1),
        ),
    ]
