# Generated by Django 5.1.7 on 2025-06-05 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_remove_userprofile_current_weight_kg_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='goal_note',
            field=models.TextField(blank=True, help_text='Optional note about your goal'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='target_weight',
            field=models.FloatField(blank=True, help_text='Target weight in kg', null=True),
        ),
    ]
