# Generated by Django 5.1.7 on 2025-06-06 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0005_remove_userprofile_goal_note_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyweightentry',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
