# Generated by Django 5.1.7 on 2025-06-06 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0006_alter_dailyweightentry_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='goal',
            field=models.FloatField(null=True),
        ),
    ]
