# Generated by Django 5.1.7 on 2025-06-06 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0007_alter_userprofile_goal'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='weekly_goal_kg',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='goal',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
