# Generated by Django 5.1.7 on 2025-06-06 19:49

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0008_userprofile_weekly_goal_kg_alter_userprofile_goal'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='progressphoto',
            options={'ordering': ['-date_added']},
        ),
        migrations.RenameField(
            model_name='progressphoto',
            old_name='image',
            new_name='photo',
        ),
        migrations.RemoveField(
            model_name='progressphoto',
            name='date',
        ),
        migrations.AddField(
            model_name='progressphoto',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='progressphoto',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
